---
- hosts: mycluster
  name: just a test to say hi
  roles:
    - say_hello
- hosts: main_box
  name: install fortune and update motd
  roles:
    - install_fortune
    - dynamic_motd
- hosts: other_boxes
  name: static motd on other boxes
  roles:
    - static_motd

