---
- name: check motd not already updated
  stat: path=/etc/profile.d/motd.sh
  register: motd
- name: update motd
  become: yes
  shell: echo /usr/games/fortune > /etc/profile.d/motd.sh
  when: motd.stat.exists == False

